/*
 * Copyright (c) 2009, Google Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of Google, Inc. nor the names of its contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#define LOG_TAG "droidboot"

#include <unistd.h>
#include <cutils/android_reboot.h>
#include <cutils/klog.h>
#include <charger/charger.h>
#include <locale.h>

#include "volumeutils/ufdisk.h"
#include "volumeutils/roots.h"
#include "aboot.h"
#include "droidboot_util.h"
#include "droidboot_plugin.h"
#include "droidboot_installer.h"
#include "droidboot.h"
#include "fastboot.h"
#include "droidboot_ui.h"

/* Generated by the makefile, this function defines the
 * register_droidboot_plugins() function, which calls all the
 * registration functions for device-specific extensions. */
#include "register.inc"

/* Default size of memory buffer for image data */
int g_scratch_size = 0;

/* Minimum battery % before we do anything */
static int g_min_battery = 10;

/* Flag to enable/disable auto paritionning from kernel command line -
   Disabled by default */
static int g_auto_partition = 0;

/* Flag to enable/disable the mount of partitions from kernel command line -
   Enabled by default */
static int g_mount_partition = 1;

/*
 * Flag to disable the display on the screen when processing fastboot command.
 * displaying the command is very slow on byt-M (4s for getvar version)
 * this flag is a temporary workaround to have faster/more reliable flash.
 * */
int g_disable_fboot_ui = 0;

static void parse_cmdline_option(char *name)
{
	char *value = strchr(name, '=');

	if (value == 0)
		return;
	*value++ = 0;
	if (*name == 0)
		return;

	if (!strncmp(name, "droidboot", 9))
		pr_info("Got parameter %s = %s\n", name, value);
	else
		return;

	if (!strcmp(name, "droidboot.scratch")) {
		g_scratch_size = atoi(value);
	} else if (!strcmp(name, "droidboot.minbatt")) {
		g_min_battery = atoi(value);
	} else if (!strcmp(name, "droidboot.autopart")) {
		g_auto_partition = atoi(value);
	} else if (!strcmp(name, "droidboot.mountpart")) {
		g_mount_partition = atoi(value);
	} else if (!strcmp(name, "droidboot.disablefbootui")) {
		g_disable_fboot_ui = atoi(value);
	} else if (!strcmp(name, "droidboot.installer_usb")) {
		strncpy(g_installer_usb_dev, value, BUFSIZ);
		g_installer_usb_dev[BUFSIZ-1] = '\0';
	} else if (!strcmp(name, "droidboot.installer_sdcard")) {
		strncpy(g_installer_sdcard_dev, value, BUFSIZ);
		g_installer_sdcard_dev[BUFSIZ-1] = '\0';
	} else if (!strcmp(name, "droidboot.installer_internal")) {
		strncpy(g_installer_internal_dev, value, BUFSIZ);
		g_installer_internal_dev[BUFSIZ-1] = '\0';
	} else if (!strcmp(name, "droidboot.installer_remote")) {
		strncpy(g_installer_remote_dev, value, BUFSIZ);
		g_installer_remote_dev[BUFSIZ-1]='\0';
	} else if (!strcmp(name, "droidboot.use_installer")) {
		g_use_installer = atoi(value);
	} else if (!strcmp(name, "droidboot.installer_file")) {
		strncpy(g_installer_file, value, BUFSIZ);
		g_installer_file[BUFSIZ-1] = '\0';
	} else {
		pr_error("Unknown parameter %s, ignoring\n", name);
	}
}

void droidboot_run_noui()
{
#ifdef USE_INSTALLER
	if (g_use_installer)
		installer_thread(NULL);
#endif

	pr_info("Listening for the fastboot protocol over USB.");
	fastboot_init(g_scratch_size * MEGABYTE);
}

extern int oem_partition_cmd_handler(int argc, char **argv);

int main(int argc, char **argv)
{
	setlocale(LC_ALL, "C.UTF-8");

	freopen("/dev/console", "a", stdout); setbuf(stdout, NULL);
	freopen("/dev/console", "a", stderr); setbuf(stderr, NULL);

	pr_info(" -- Droidboot %s for %s --\n", DROIDBOOT_VERSION, DEVICE_NAME);
	strncpy(g_installer_file, DEFAULT_INSTALLER_FILENAME, BUFSIZ);
	import_kernel_cmdline(parse_cmdline_option);

	aboot_register_commands();
	register_droidboot_plugins();

	droidboot_ui_init();
	/* Enforce a minimum battery level */
	if (g_min_battery != 0) {
		pr_info("Verifying battery level >= %d%% before continuing\n",
				g_min_battery);
		klog_init();
		klog_set_level(8);

		switch (charger_run(g_min_battery, MODE_NON_CHARGER,
					POWER_ON_KEY_TIME,
					BATTERY_UNKNOWN_TIME,
					UNPLUGGED_SHUTDOWN_TIME,
					CAPACITY_POLL_INTERVAL)) {
		case CHARGER_SHUTDOWN:
			android_reboot(ANDROID_RB_POWEROFF, 0, 0);
			break;
		case CHARGER_PROCEED:
			pr_info("Battery level is acceptable\n");
			break;
		default:
			pr_error("mysterious return value from charger_run()\n");
		}
	}

	droidboot_init_table();

	/* Unset previous settings before switching to fastboot */
	property_set("sys.usb.config", "none");

	load_volume_table();

	// Create automatically partitions if they do not exist
	// and if specified in the kernel command line
	if (ufdisk_need_create_partition()) {
		if(g_auto_partition == 1) {
			// set the property to allow the partitioning
			property_set("sys.partitioning", "1");
			char *path[] = {0,"/etc/partition.tbl"};
			oem_partition_cmd_handler(2,(char **)path);
		}
	}

	// Unless specified in the kernel command line, by default,
	// the partitions are mounted !
	if(g_mount_partition  == 1)
		// set the property to mount the partitions
		property_set("sys.partitioning", "0");

	droidboot_run();

	/* Shouldn't get here */
	return 0;
}
