PRODUCT_PROPERTY_OVERRIDES += \
    dalvik.vm.heapstartsize=5m \
    dalvik.vm.heapgrowthlimit=48m \
    dalvik.vm.heapsize=96m \
    dalvik.vm.heaptargetutilization=0.9 \
    dalvik.vm.heapminfree=512k \
    dalvik.vm.heapmaxfree=2m \
    dalvik.jit.code_cache_size=307200 \
    dalvik.jit.threshold=255
