DEVICE_PATH := $(LOCAL_PATH)
DEVICE_CONF_PATH := $(LOCAL_PATH)/config
PLATFORM_PATH := $(DEVICE_PATH)/..
PLATFORM_CONF_PATH := $(PLATFORM_PATH)/config
COMMON_PATH := $(PLATFORM_PATH)/../common
COMMON_PLUS_PATH := $(PLATFORM_PATH)/../common_plus
